singleQuote: true
semi: false
printWidth: 120
trailingComma: none

plugins:
  - '@trivago/prettier-plugin-sort-imports'

importOrder:
  - ^@core/(.*)$
  - ^@server/(.*)$
  - ^@ui/(.*)$
  - '^[./]'
importOrderSeparation: true
importOrderSortSpecifiers: true
